name: "Deploy WordPress to WP Engine"
branding:
  icon: "upload-cloud"
  color: "blue"
description: "Deploy WordPress projects to a WP Engine account using SSH Gateway"
inputs:
  WPE_ENV_NAME:
    description: "The WP Engine environment to deploy to that is labeled as Production, Staging or Development."
    required: false
  WPE_SSHG_KEY_PUBLIC:
    description: "The public RSA key you save in the WP Engine User Portal"
    required: true
  WPE_SSHG_KEY_PRIVATE:
    description: "The private RSA key you will save in the Github Secrets"
    required: true
  TPO_SRC_PATH:
    description: "An optional source directory to deploy other than the root directory that is being versioned."
    default: ""
    required: false
  TPO_PATH:
    description: "An optional destination directory to deploy to other than the WordPress root."
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: sh