name: Create or update tags
description: Maintains major, minor, and patch version tags.
branding:
  icon: 'upload-cloud'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - run: "${{ github.action_path }}/update-tags.sh"
      shell: bash