name: Publish release tags
description: Ensures major, minor, and patch version tags for a given version.
inputs:
  version:
    description: 'Patch version to publish.'
    required: true
outputs:
  published:
    description: 'Whether a new version was published.'
    value: ${{ steps.publish.outputs.PUBLISHED }}
runs:
  using: 'composite'
  steps:
    - id: publish
      run: "${{ github.action_path }}/publish.sh ${{ inputs.version }}"
      shell: bash